### ISSUE TITLE
Some improper locking bugs

### ISSUE THREAD

**Issue by ryancaicse** [anlsys/aml#215]
Dear developers, in below codes, the lock `data->lock ` (Line **572**) is directly destroyed (Line **632**) without releasing before, which is a undefined behaviour, according to the pthread APIs. It's better to release it before destroying it.

https://github.com/anlsys/aml/blob/e834133fb3123da613bd85191b8474d28889ecae/src/allocator/buddy.c#L575-L602

**Comment by ryancaicse** [comment]
@NicolasDenoyelle Could you take a look? Thanks

**Comment by NicolasDenoyelle** [comment]
@ryancaicse Thanks for noticing this. 
I am going to send a PR about it today.
In the future, if you find easy fixes like that feel free to send us a PR about it. Contributors are welcome.
