### ISSUE TITLE
Autoconf should fail on mandatory lib missing

### ISSUE THREAD

**Issue by iskra-anl** [anlsys/aml#52]
In GitLab by @perarnau on Jan 15, 2020, 13:18

By default AC_CHECK_LIB by itself doesn't kill the compilation, resulting in many tests failing later for no obvious reasons.

For the libraries that we have indicated as mandatory, we should use AC_CHECK_LIB(,,,AC_MSG_ERROR()) to fail the test quickly and cleanly.

**Comment by perarnau** [comment]
Fixed since then
