### ISSUE TITLE
[doc] Replicaset doxygen contains errors in function documentation

### ISSUE THREAD

**Issue by iskra-anl** [anlsys/aml#68]
In GitLab by @perarnau on Sep 29, 2020, 10:45

The main replicaset header has errors in doxygen docs for `init`.

**Comment by iskra-anl** [comment]
In GitLab by @NicolasDenoyelle on Mar 15, 2021, 12:54

mentioned in merge request !173

**Comment by iskra-anl** [comment]
In GitLab by @perarnau on Mar 15, 2021, 13:50

mentioned in commit 6f236d1f1c3fdc876a8b1df28a2e58ed776e106c

**Comment by perarnau** [comment]
Fixed already.
